---
# tasks file for configure
  - name: Logs systemctl permanente
    replace:
      path: /etc/systemd/journald.conf
      regexp: '^#Storage=auto'
      replace: 'Storage=persistent'

  - name: Desativando touchpad 
    blockinfile:
      path: /etc/udev/rules.d/01-touchpad.rules
      create: yes
      block: |
        SUBSYSTEM=="input", KERNEL=="mouse[0-9]*", ACTION=="add", ENV{DISPLAY}=":0", ENV{XAUTHORITY}="/home/{{ usuario }}/.Xauthority", RUN+="/usr/bin/synclient TouchpadOff=1"
        SUBSYSTEM=="input", KERNEL=="mouse[0-9]*", ACTION=="remove", ENV{DISPLAY}=":0", ENV{XAUTHORITY}="/home/{{ usuario }}/.Xauthority", RUN+="/usr/bin/synclient TouchpadOff=0"
  
  - name: Ativando pacotes recomendados
    replace:
      path: /etc/apt/apt.conf.d/00recommends
      regexp: '"false"'
      replace: '"true"'
    
  - name: Setando Swappiness para 5
    lineinfile:
      path: /etc/sysctl.conf
      line: "vm.swappiness=5"

  - name: Criando link simbolico Tilix
    file:
      src: /etc/profile.d/vte-2.91.sh
      dest: /etc/profile.d/vte.sh
      owner: "{{ usuario }}"
      group: "{{ usuario }}"
      state: link
  
  - name: Alterando a senha do root
    user: 
      name: root 
      update_password: always 
      password: "{{root_password}}"
  
  - name: Importando tarefa para configurar teclado
    import_tasks: teclado.yml
