---
# tasks file for install
  - name: ADICIONANDO | Chave para instalacao do Google Chrome
    apt_key: 
      url: https://dl-ssl.google.com/linux/linux_signing_key.pub 
      state: present

  - name: ADICIONANDO | Repositorio Google Chrome
    apt_repository:
      repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
      state: present
      filename: dl_google_com_linux_chrome_deb.list
      update_cache: yes

  - name: INSTALANDO | Google Chorme Stable
    apt:
      name: google-chrome-stable
      state: present