---
# tasks file for install
  - name: Instalando Pacotes Basicos
    apt:
      name: "{{ pacotes_basicos }}"
      state: present
      update_cache: yes
  
  - name: Instalando Pacotes Multimidia
    apt:
      name: "{{ pacotes_multimidia }}"
      state: present
  
  - name: Instalando Codecs Pacotes Codecs
    apt:
      name: "{{ pacotes_codecs }}"
      state: present

  - name:  Instalando Pacotes Rede
    apt:
      name: "{{ pacotes_rede }}"
      state: present

  - name:  Instalando Pacotes Manutencao
    apt:
      name: "{{ pacotes_manutencao }}"
      state: present

  - name:  Instalando Pacotes Dev
    apt:
      name: "{{ pacotes_dev }}"
      state: present

  - name: Instalando Repositorio Numix
    raw: apt-add-repository ppa:numix/ppa -y
    tags:
      ppas
      add-ppas

  - name: Instalando Repositorio Tilix
    raw: add-apt-repository ppa:webupd8team/terminix -y 
    tags: 
      ppas
      add-ppas

  - name: Instalando Repositorio Notepadqq
    raw: add-apt-repository ppa:notepadqq-team/notepadqq -y  
    tags:
      ppas
      add-ppas

  - name: Instalando Pacotes dos PPAs
    apt:
      name: "{{ pacotes_ppa }}"
      state: present
    tags:
      ppas
  
  - name: Instalando Steam
    apt:
      name: steam
      state: present
    when: steam == "TRUE"
    tags:    
      steam  

  - name: Instalando VS Code
    import_tasks: code.yml
    tags: 
      code

  - name: Instalando Google Chrome
    import_tasks: chrome.yml
    tags: 
      chrome
  
  - name: Instalando nvidia
    import_tasks: nvidia.yml
    when: nvidia_driver == "TRUE"
    tags: 
      nvidia 

  - name: Instalando docker
    import_tasks: docker.yml
    tags: 
      docker

  - name: Removendo pacotes desnecessarios
    apt: 
      name: ['ed', 'nano', 'vim-tiny']
      state: absent
    tags:
      remove-pacotes

  - name: Limpando cache de pacotes
    apt:
      autoremove: yes
      purge: yes

  - name: Atualizando todos os pacotes
    apt: 
      update_cache: yes
      upgrade: full
